# Generated by Django 4.0.1 on 2022-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Vendeur', 'SELLER'), ('Client', 'USER')], max_length=7),
        ),
    ]
