# Generated by Django 4.0.1 on 2022-04-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
