# Generated by Django 4.0.1 on 2022-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statut', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ManyToManyField(related_name='sous_categories', to='base.Categories')),
            ],
            options={
                'verbose_name': 'Sous-Catégorie',
                'verbose_name_plural': 'Sous-Catégories',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
